version: 2
updates:
 - ignore:
      - dependency-name: '*'
        update-types: ["version-update:semver-patch"]

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Java
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
