name: Java CI with Maven

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up JDK
      uses: actions/setup-java@v3.12.0
      with:
        java-version: 19
        distribution: 'zulu'
        cache: 'maven'

    - name: Build with Maven
      run: mvn --batch-mode --strict-checksums verify

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2.9.0
      if: ${{ github.actor != 'dependabot[bot]' }}
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        check_name: Unit Test Results
        files: '**/target/surefire-reports/*.xml'
        report_individual_runs: true
        deduplicate_classes_by_file_name: false

    - name: Run SpotBugs from Maven
      run: mvn --batch-mode ${SPOTBUGS_PLUGIN} ${SPOTBUGS_OPTIONS}
      env:
        SPOTBUGS_PLUGIN: com.github.spotbugs:spotbugs-maven-plugin:4.7.2.1:spotbugs
        SPOTBUGS_OPTIONS: -Dspotbugs.xmlOutput=true -Dspotbugs.effort=max -Dspotbugs.threshold=low -Dspotbugs.failOnError=true

    - name: Publish SpotBugs report
      uses: jwgmeligmeyling/spotbugs-github-action@master
      if: ${{ github.actor != 'dependabot[bot]' }}      
      with:
        path: '**/target/spotbugsXml.xml'
     
    - name: Run Checkstyle from Maven
      run: mvn --batch-mode  checkstyle:checkstyle -Dcheckstyle.config.location=google_checks.xml -Dcheckstyle.suppressions.location=./checkstyle-suppressions.xml

    - name: Publish Checkstyle report
      if: ${{ github.actor != 'dependabot[bot]' }}    
      uses: jwgmeligmeyling/checkstyle-github-action@master
      with:
        path: '**/target/checkstyle-result.xml'
        
    - name: Run PMD from Maven
      run: mvn --batch-mode pmd:check pmd:cpd -DlinkXRef=false
      
    - name: Publish PMD reports
      if: ${{ github.actor != 'dependabot[bot]' }}    
      uses: jwgmeligmeyling/pmd-github-action@master
      with:
        path: '**/target/??d.xml'
